import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Navigation from "./components/navigation";
import { Wrapper } from "./wrapper";
import { ThemeProvider } from "./context/theme-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    default: "Next.js Demo",
    template: "%s | Next.js",
  },
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <ThemeProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <header className="text-center text-white p-4 bg-slate-900">
              <Navigation />
            </header>
            <Wrapper>{children}</Wrapper>
            <footer className="text-center text-white p-4 bg-slate-900">
              <p>This is footer</p>
            </footer>
          </body>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  );
}
